name: Bug Report
description: Report a bug in passport-client-certificate-auth
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please complete the sections below so the issue can be reproduced quickly.

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Output of `node --version`
      placeholder: "v24.0.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: OS and version
      placeholder: "Ubuntu 24.04 / macOS 15 / Windows 11"
    validations:
      required: true

  - type: dropdown
    id: module-system
    attributes:
      label: Module System
      options:
        - ESM (import)
        - CommonJS (dynamic import from CJS)
    validations:
      required: true

  - type: dropdown
    id: certificate-source
    attributes:
      label: Certificate Source
      description: How does your app receive the client certificate?
      options:
        - Direct TLS socket (no reverse proxy)
        - "AWS ALB (`certificateSource: 'aws-alb'`)"
        - "Envoy / Istio (`certificateSource: 'envoy'`)"
        - "Cloudflare (`certificateSource: 'cloudflare'`)"
        - "Traefik (`certificateSource: 'traefik'`)"
        - nginx (custom header)
        - HAProxy (custom header)
        - Other reverse proxy / load balancer
    validations:
      required: true

  - type: textarea
    id: strategy-config
    attributes:
      label: Strategy Configuration
      description: Include your `new Strategy(...)` call and options.
      render: js
      placeholder: |
        passport.use(new Strategy({
          certificateSource: 'envoy',
          verifyHeader: 'x-forwarded-client-cert-verified',
          verifyValue: 'true'
        }, (cert, done) => {
          // ...
        }));
    validations:
      required: true

  - type: textarea
    id: proxy-config
    attributes:
      label: Reverse Proxy Configuration
      description: If using a proxy/load balancer, include relevant TLS/header forwarding config.
      render: text
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. Configure strategy with ...
        2. Send request with ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What happened instead? Include stack traces/logs.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant details.
    validations:
      required: false
