name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement. Please describe the feature and why it helps your mTLS Passport integration.

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should this behave? Include API examples if possible.
      render: js
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What workarounds or alternatives did you evaluate?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Related issues, links, logs, or design notes.
    validations:
      required: false
